title: Virtually(Creative)
baseURL: /
params:
  color_scheme: light
  accent_color: blue
  base_font: system-sans
  header:
    title: Virtually(Creative)
    logo: images/Logo-Big.png
    logo_alt: Virtually Creative Logo
    has_nav: true
    nav_links:
      - label: Main
        url: /
        style: link
      - label: Work
        url: /portfolio/
        style: link
      - label: Blog
        url: /blog/
        style: link
      - label: About
        url: /about/
        style: link
      - label: Pricing
        url: /pricing/
        style: link
        icon: dribbble
        new_window: false
        no_follow: false
        type: action
      - label: Contact
        url: /contact/
        style: button
  footer:
    content: 'Really, you read this part? Neato! 2021 '
    has_social: true
    social_links:
      - label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: icon
        icon: linkedin
        new_window: true
      - label: Github
        url: 'https://www.instagram.com/'
        style: icon
        icon: github
        new_window: true
      - label: Twitter
        url: 'https://twitter.com/'
        style: icon
        icon: twitter
        new_window: true
  domain: 'https://virtuallycreative-core-421e2.netlify.app'
  favicon: images/Logo Arrows.png
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
